server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bulletin_board
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  token:
    secret: secret
    expired: 3600000
